### ISSUE TITLE
Pull Request Details

### ISSUE THREAD

**Issue by leocreatini** [styled-components/jest-styled-components#10]
Hi @MicheleBertoli,

First time I am making a PR in an open-source project and just wanted to know your expectations.

I added the React web toHaveStyle matcher. It's passing the linting and works as expected with Enzyme. I even added a bit of documentation to the Readme. I think I need to add comments to the code itself, and maybe change the anonymous arrow functions to declared functions to make it look like the rest of the code base.

Let me know what you think!

Thanks

**Comment by MicheleBertoli** [comment]
Thanks for opening the issue @leocreatini.
I'm super excited that this is going to be your first contribution.

There are no rules in this repo, except that the code should make testing a delightful experience :)

Please use arrow functions when they make sense and regular ones otherwise.
Also, thank for updating the README as well. Once is merged, I'm going to add the screenshots using my theme (for consistency) if you don mind.

Looking forward to receiving a PR.

**Comment by leocreatini** [comment]
Thanks, @MicheleBertoli, and please add screenshots when you can, I like consistency :+1: 

I have a minor hitch, it says that I do not have permission to make a PR.
Do you know what the issue might be?

**Comment by kentcdodds** [comment]
You might like to watch this free video course that could help a bit: http://makeapullrequest.com 😀

**Comment by leocreatini** [comment]
@kentcdodds Thanks, I love egghead (on my second year of subscription). It seems my issue came down to corporate firewall :sob:. Will try again when I get home.
