### ISSUE TITLE
Why resetStyleSheet()

### ISSUE THREAD

**Issue by rpellerin** [styled-components/jest-styled-components#100]
Hi,
Thanks for developing such a useful library!
Just wondering... why do you call `resetStyleSheet()` in `src/index.js`?
Thanks!

**Comment by MicheleBertoli** [comment]
Hello @rpellerin, thank you very much for your feedback.
The reset call was added in #25 by @rikukissa, and it's needed because it [creates](https://github.com/styled-components/styled-components/blob/master/src/models/StyleSheet.js#L148) a new instance of the internal Styled Components's StyleSheet.
I hope this answers your question.

**Comment by rpellerin** [comment]
Thanks!
