### ISSUE TITLE
react-testing-library `rerender` method

### ISSUE THREAD

**Issue by JoosepAlviste** [styled-components/jest-styled-components#175]
Hey. I just tried out the support for react-testing-library, but found that using the [rerender](https://github.com/kentcdodds/react-testing-library#rerender) method does not generate a nice snapshot. Here's my small example:

```
it('renders correctly', () => {
  const { container, rerender } = render(<Button>Test</Button>);

  expect(container.firstChild).toMatchSnapshot();

  rerender(<Button color="blue">Test</Button>);

  expect(container.firstChild).toMatchSnapshot();
});
```

And the generated snapshots file includes both of the snapshots. The first one using `render` is ok:

```
exports[`renders correctly 1`] = `
.c0 {
  // ...
}

.c0:focus {
  // ...
}

<button
  class="c0 "
  type="submit"
>
  Test
</button>
`;
```

But the second one, using `rerender`, still has those class names which offer no information:

```
exports[`renders correctly 2`] = `
<button
  class="sc-bwzfXH iSxoCd sc-bdVaJa bmREAD"
  type="submit"
>
  Test
</button>
`;
```

As a workaround I can just use render again and declare another container variable, but it's less convenient. There's a chance I just misunderstood the `rerender` function though, as I just started using react-testing-library.

**Comment by MicheleBertoli** [comment]
Hello @JoosepAlviste, thanks for opening this issue.

I confirm you are using `rerender` in the correct way.
However, this library [marks the received nodes as "seen"](https://github.com/styled-components/jest-styled-components/blob/master/src/styleSheetSerializer.js#L133) to avoid issues with children.
That's why the second expectation doesn't go through the serialiser.

A super-hacky way to solve the issue (not recommended), is to remove the added property before the second expectation:

```js
delete container.firstChild['__jest-styled-components__']
```

My advice would be to run two separate tests for the different props.

I hope this helps.

**Comment by kachkaev** [comment]
@MicheleBertoli could a call to the delete statement be automated somehow? Also had multiple `toMatchSnapshot()` calls and it took me a while to dig out this issue.

**Comment by esetnik** [comment]
I have the same issue. @MicheleBertoli can you elaborate on why the delete suggestion isn't a good idea?
