### ISSUE TITLE
Enzyme shallow with toMatchStyledComponentsSnapshot

### ISSUE THREAD

**Issue by miazukee** [styled-components/jest-styled-components#21]
Hey!

I'm just trying out your module. I'm running into something strange. Basically, I'm not getting the same results you showed in the preview screenshot.

The `toMatchStyledComponentsSnapshot` generates a snapshot that doesn't contain the detailed styles of the class.

The documentation being a bit short, am I doing something wrong here?
```
const MyStyledComponent = styled.div`
  background-color: rgba(0, 0, 0, 0.3);
  width: 100%;
  height: 8px;
  border-radius: 4px;
  margin: 6px 0;
`;
```
The test:
```
let wrapper;
beforeEach(() => {
  wrapper = shallow(<MyStyledComponent {...props} />);
});

it('should match the snapshot', () => {
  expect(wrapper).toMatchStyledComponentsSnapshot();
});
```
Snapshot result:
```
exports[`should match the snapshot 1`] = `
ShallowWrapper {
  ...
}...
```

When `mount(..)` the component and using `toHaveStyleRule` I get `Cannot read property 'styleSheet' of undefined`.

Thanks!

### Versions in use:
jest: v20.0.4
styled-components: v1.4.6
jest-styled-components: v2.1.1
enzyme: v2.8.2

**Comment by MicheleBertoli** [comment]
Hello @miazukee, thanks for opening the issue.
The `mount` function from Enzyme doesn't work with this package because it needs `jsdom`.
However, the `shallow` rendering works pretty well (as you can see in the [test folder](https://github.com/styled-components/jest-styled-components/blob/master/test/index.spec.js#L47)).
From what I can see here, it looks like you are missing the [`enzyme-to-json`](https://www.npmjs.com/package/enzyme-to-json) serializer.
