### ISSUE TITLE
Problem with multiple children rule

### ISSUE THREAD

**Issue by duskpoet** [styled-components/jest-styled-components#227]
Whenever there is multiple children in a single rule, generated snapshots contain randomized hashes in class names. Example:
```(jsx)
const IconPlus = styled(Plus)``; //external react component with className prop
const IconMinus = styled(Minus)``;
export const Expander = styled('div')`
   ...
   ${IconPlus}, ${IconMinus} {
      color: black;
   }
`;
```

Then generated snapshot has something like this:
```
.c1 .c2,
.c1 .sc-hqyNC {
  color: black;
}

```

**Comment by Madebymaurice** [comment]
Hi, does all your component are styled with styled-components ?
I'm having the same comportment because some imports are styled with glamorous for me (it's normal as we work for remove glamorous for styled-components).
Generally this append when `jest-styled-components` could not read the component.

**Comment by duskpoet** [comment]
Yea, we do have external components that are not written with styled.
Any workaround? Right now I decoupled this css rule, but it's not very appealing.

**Comment by Madebymaurice** [comment]
No workaround for me because my work is to progressively change glamorous for styled-components. Sorry
