### ISSUE TITLE
[Documentation] About .toMatchStyledComponentsSnapshot method

### ISSUE THREAD

**Issue by lgraziani2712** [styled-components/jest-styled-components#3]
It seems like there is no need to use `.toMatchStyledComponentsSnapshot`.

Using `.toMatchSnapshot` has the same effect once the addon is configured.

Is good to know to prevent unnecessary refactor 🙂

Thanks!

**Comment by MicheleBertoli** [comment]
Thanks @lgraziani2712 for opening the issue.
However, there is an important difference between `toMatchSnapshot` and  `toMatchStyledComponentsSnapshot`.
The latter, in fact, marks the non-relevant changes (e.g. the class names) with a different color in order to make it easier to spot what really changed.

**toMatchSnapshot**

<img width="461" alt="screen shot 2017-03-19 at 19 45 41" src="https://cloud.githubusercontent.com/assets/1308971/24084164/022a3f62-0cdd-11e7-943f-7c40b88c068e.png">

**toMatchStyledComponentsSnapshot**

<img width="479" alt="screen shot 2017-03-19 at 19 46 03" src="https://cloud.githubusercontent.com/assets/1308971/24084165/049b200e-0cdd-11e7-8c8e-7f54f5e02989.png">
