### ISSUE TITLE
New style of classes not showing after upgrading.

### ISSUE THREAD

**Issue by joetidee** [styled-components/jest-styled-components#63]
I have just upgraded to 4.2.1 , but the new static classnames are not being generated. Is there anything else that I need to do in order to get them working, like update my current snapshots?

**Comment by MicheleBertoli** [comment]
Hello @joetidee, it's hard to give you a proper answer without seeing a bit of code.
What should happen would be that when you run the tests for the first time with v4 (coming from v3), ALL your snapshots fail because of the new static class names.
At that point, you just press `u` and you are good to go again.

Please let me know if you can provide more details, I'll be happy to help.

**Comment by MicheleBertoli** [comment]
Hello @joetidee, it's hard to give you a proper answer without seeing a bit of code.

What should happen would be that when you run the tests for the first time with v4 (coming from v3), ALL your snapshots fail because of the new static class names.
At that point, you just press `u` and you are good to go again.

Please let me know if you can provide more details, I'll be happy to help.

**Comment by joetidee** [comment]
Thanks Michele. We did update the templates, however, we couldn't see the new template format coming through in the new templates that were generated. In the end, the only way we got the new templates to come through was to place the `import 'jest-styled-components';` after all our other imports. Not sure why this would need to be the case (?)

**Comment by MicheleBertoli** [comment]
I'm happy to hear it worked : )
