### ISSUE TITLE
Style rules are always included

### ISSUE THREAD

**Issue by igl** [styled-components/jest-styled-components#69]
Is it possible to have only the class names substituted?

It makes no sense to me to include all css rules in the snapshot.
I rather have explicit toHaveStyleRule checks for important changes.

- Whenever i have a change in my theme-file i break **all** tests, all the time.
- When i break all tests all the time i get lazy.
- When i (or my coworkers) get lazy i press and hold-down U
- This is very very very bad.

**Comment by MicheleBertoli** [comment]
Hello @igl, this is an interesting question.
I strongly believe snapshots should fail when things change. 
In particular, styled components snapshots should fail when the style changes (that's why I decided to put the style to the snapshots in the first place :)).
That said, if your problem is only related to themes you might want to consider [mocking](https://facebook.github.io/jest/docs/jest-object.html#jestmockmodulename-factory-options) it.

However, If you just want to use regular snapshots and get rid of the styled components class names, I suggest you write your own serializer. 

Something like this:

```js
expect.addSnapshotSerializer({
  test(val) {
    return val.props.className
  },
  print(val, print) {
    delete val.props.className
    return print(val)
  },
})
```
```js
test('bye bye className', () => {
  const Button = styled.button`
    color: red;
  `
  const tree = renderer.create(<Button />).toJSON()
  expect(tree).toMatchSnapshot()
})
```

Which generates the following snapshot:

```js
exports[`bye bye className 1`] = `<button />`;
```

I hope this helps.
