### ISSUE TITLE
How does this behave in 2 SC projects using together

### ISSUE THREAD

**Issue by tleunen** [styled-components/jest-styled-components#70]
Just a question, not a bug @MicheleBertoli. I'm evaluating using SC and especially this jest plugin to make it work better since SC is changing the css classnames too many times (even sometimes when no css has changed).

Lets say I'm using a UI library (MyCustomBootstrapUI), which is built using styled-components.

I have my own app, called MySuperApp, which is also using styled-components, with jest-styled-components to have super nice snapshots.

MySuperApp is using MyCustomBootstrapUI v1. Then, MyCustomBootstrapUI gets updated to v1.1. One component changed to add a new css prop.

When updating MySuperApp to use the new UI v1.1, is it expected to have a snapshot difference/conflict because of the new css prop in the UI library?
From what I understand, there will be a difference, since jest-styled-component is outputing the css into the snapshots for all SC components. So, I wonder if it's expected, if we should have that or not. It could be nice in some ways I guess, to easily see in the project side what has changed, but it could also add a lot of noises too?

**Comment by MicheleBertoli** [comment]
Hello @tleunen, thanks for opening this issue.

I strongly believe the greatest benefit snapshot testing provides is telling you when things change.
Therefore, when your UI library is upgraded from 1 to 1.1 you want to know what are the differences with the current output.
However, I can see how this could make the snapshots noisy in some scenario.

I still think snapshot testing would be helpful in your case, but you might want to implement some workarounds to avoid having too many failing tests when a single dependency changes.
For example: when you are testing `MySuperApp`, you could [mock](https://facebook.github.io/jest/docs/mock-functions.html#content) the `MyCustomBootstrapUI` components so that they don't generate any style.
Otherwise, you could play with [Enzyme's shallow](http://airbnb.io/enzyme/docs/api/shallow.html) rendering and make sure only your components get rendered.

Please let me know if this makes sense for you, and if you need more practical help and examples.

**Comment by tleunen** [comment]
Thanks for the response. I'm just in the process of migrating to styled-components so it was more a question without real testing first. I do believe it will be more useful than the opposite in an app too, so you always know what changes.
