### ISSUE TITLE
More explicit classname in snapshot

### ISSUE THREAD

**Issue by Spy-Seth** [styled-components/jest-styled-components#95]
This module do a perfect job to make the styled component classname predictive and allow us to use snapshot testing thanks for this 👍 

After starting to use `babel-plugin-styled-components` in front, I feel in love with more descriptive class name ` <button class="Button-asdf123 asdf123" />`. I'm asking myself if in test it could also be interesting to add the origin of the style in the classname. `c0`, `c1`, ..., `c42` are no really helpfull to find witch component is attached to this style. 

Did you think it could be a good idea to generate classname more descriptive: `c0-Button` or `Button_Inner_c3`? This could really help on big snapshots

**Comment by MicheleBertoli** [comment]
Thank you very much @Spy-Seth, I'm glad you find this package helpful.

I guess it was just an example but it's worth saying that if you have `c42` (42 class names) it means the tree you are testing is too big, and you should consider testing sub-components separately.

In general, I agree that adding the component name to the class name would make the snapshot easier to read.
However, adding component-related information to the class names also means that any time any one of these information change, the class names are broken as well - which would make the test output noisy.

I hope this makes sense, but feel free to submit a PR if you think this improves the DX.
It would be great to see a prototype of this, in order to figure out what are the pros and the cons.
